---
name: Molecule
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                molecule_distro: [amazonlinux2, centos8, ubuntu1804, debian9]

        steps:
            - uses: actions/checkout@v1
              with:
                  path: ansible-role-terraform
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.6
            - name: Install dependencies
              run: |
                  sudo apt install docker
                  python3 -m pip install --upgrade pip
                  python3 -m pip install molecule yamllint ansible-lint docker
            - name: Test with molecule
              run: |
                  molecule converge
              env:
                  MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
                  ROLE_NAME: ansible-role-terraform
            - name: Upload to Ansible-Galaxy
              run: |
                  GIT_USER=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
                  GIT_REPO=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 )
                  ansible-galaxy role import --api-key $GALAXY_API_KEY $GIT_USER $GIT_REPO
              env:
                  GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
